export const TORONTO_CAMPUS_OPTIONS = [
  "University of Toronto - St. George",
  "University of Toronto - Scarborough",
  "Toronto Metropolitan University - Downtown Campus",
  "York University - Keele",
  "York University - Glendon",
  "George Brown College - Casa Loma",
  "George Brown College - St. James",
  "George Brown College - Waterfront",
  "Humber Polytechnic - North",
  "Humber Polytechnic - Lakeshore",
  "Humber Polytechnic - Downtown / IGS",
  "OCAD University - Main Campus",
  "Seneca Polytechnic - Newnham",
  "Seneca Polytechnic - Seneca@York",
  "Centennial College - Progress",
  "Centennial College - Morningside",
  "Centennial College - Ashtonbee",
  "Centennial College - Story Arts",
];
