import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";

import { AppLayoutShell } from "@/components/app-layout-shell";
import { createClient } from "@/utils/supabase/server";
import { LanguageProvider } from "@/context/LanguageContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const supabase = createClient(cookieStore);
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const displayName =
    [
      user?.user_metadata?.first_name,
      user?.user_metadata?.last_name,
    ]
      .filter(Boolean)
      .join(" ")
      .trim() || "Student";

  const sidebarUser = user
    ? {
        name: displayName,
        email: user.email ?? "",
        school: user.user_metadata?.school ?? "Toronto student",
        avatar: user.email
          ? `https://avatar.vercel.sh/${encodeURIComponent(user.email)}`
          : "",
      }
    : null;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <LanguageProvider>
          <AppLayoutShell user={sidebarUser}>
            {children}
          </AppLayoutShell>
        </LanguageProvider>
      </body>
    </html>
  );
}